virtualStoreType: global

minimumReleaseAgeExclude:
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@oxlint-tsgolint/*"
  - "@vitest/*"
  - oxc-config-hope
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - tsdown
  - vitest

packageExtensions:
  "@codecov/rollup-plugin":
    peerDependenciesMeta:
      rollup:
        optional: true

  conventional-changelog-preset-loader:
    peerDependencies:
      conventional-changelog-conventionalcommits: ^10.0.0
    peerDependenciesMeta:
      "conventional-changelog-core":
        optional: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 720

trustPolicyExcludePrune: true
