name: Build and Linter Check

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          runtime: node@24

      - name: Install deps
        run: pnpm ci

      - name: Build with bundle analysis
        env:
          BUNDLE_ANALYSIS: true
        run: pnpm run build

      - name: Linter
        run: pnpm run lint:check
